#!/bin/bash
#SBATCH -A uot193
#SBATCH --job-name="join.local"
#SBATCH --output="join.local.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem=16G
#SBATCH --export=ALL 
#SBATCH --time=10

module load cpu/0.15.4 gcc/7.5.0 openjdk hadoop/3.2.2
SW=/expanse/lustre/projects/uot193/fegaras
export PIG_HOME=$SW/pig-0.17.0
PATH="$PIG_HOME/bin:$PATH"
export TMPDIR=$HOME/tmp

rm -rf output
pig -x local join.pig
